const categoriesData = [
  {
    name: 'Anime Figures',
    slug: 'anime-figures',
    description: 'Authentic Japanese scale figures, Nendoroids, and collector statues from top sculptors.',
    icon: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=1200&q=80',
    subCategories: ['Scale 1/7 & 1/4', 'Nendoroid', 'Pop Up Parade', 'Figma & Action', 'Statues'],
  },
  {
    name: 'Warhammer 40k',
    slug: 'warhammer-40k',
    description: 'Miniatures, combat patrols, battleforces, and rulebooks for Warhammer 40,000, AoS, and Kill Team.',
    icon: 'ShieldAlert',
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    subCategories: ['Space Marines & Imperium', 'Chaos Space Marines', 'Xenos Factions', 'Kill Team', 'Age of Sigmar'],
  },
  {
    name: 'Board Games',
    slug: 'board-games',
    description: 'Award-winning tabletop strategy games, eurogames, worker placement, and cooperative thematic games.',
    icon: 'Dices',
    image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=1200&q=80',
    subCategories: ['Heavy Strategy & Euro', 'Thematic & Adventure', 'Engine Building', 'Family & Gateway', 'Cooperative'],
  },
];

const usersData = [
  {
    name: 'Admin Commander',
    email: 'admin@hobbyvault.com',
    password: 'Admin@123456',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=256&q=80',
    shippingAddress: {
      fullName: 'Admin Operations',
      phone: '+1 (555) 019-2834',
      street: '742 Evergreen Citadel',
      city: 'Sector Prime',
      state: 'California',
      postalCode: '90210',
      country: 'USA',
    },
  },
  {
    name: 'Alex Mercer (Collector)',
    email: 'customer@hobbyvault.com',
    password: 'Customer@123456',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=256&q=80',
    shippingAddress: {
      fullName: 'Alex Mercer',
      phone: '+1 (555) 847-2910',
      street: '124 Hobbyist Way, Suite 4B',
      city: 'Seattle',
      state: 'Washington',
      postalCode: '98101',
      country: 'USA',
    },
  },
];

const productsData = [
  // 1. Anime Figures
  {
    name: 'Fate/Grand Order - Saber Alter (Kimono Ver.) 1/7 Scale Figure',
    slug: 'fate-grand-order-saber-alter-kimono-1-7',
    sku: 'ALT-FGO-001',
    categorySlug: 'anime-figures',
    subCategory: 'Scale 1/7 & 1/4',
    brand: 'Alter',
    price: 249.99,
    discountPrice: 229.99,
    stockCount: 14,
    images: [
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'From the popular mobile game Fate/Grand Order comes a gorgeous 1/7 scale figure of Altria Pendragon (Alter) in a luxurious traditional dark embroidered kimono with translucent flow effects.',
    attributes: {
      scale: '1/7 Scale',
      character: 'Saber Alter',
      series: 'Fate/Grand Order',
      material: 'PVC & ABS',
    },
    isPreOrder: false,
    rating: 4.9,
    numReviews: 48,
    soldCount: 92,
    featured: true,
  },
  {
    name: 'Spy x Family - Nendoroid Anya Forger',
    slug: 'spy-x-family-nendoroid-anya-forger',
    sku: 'GSC-NEN-1900',
    categorySlug: 'anime-figures',
    subCategory: 'Nendoroid',
    brand: 'Good Smile Company',
    price: 59.99,
    discountPrice: 0,
    stockCount: 32,
    images: [
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'The beloved telepathic daughter Anya Forger from Spy x Family gets her official Nendoroid release! Includes her iconic smug faceplate, smiling faceplate, and her Chimera plush doll.',
    attributes: {
      scale: 'Nendoroid',
      character: 'Anya Forger',
      series: 'Spy x Family',
      material: 'PVC & ABS',
    },
    isPreOrder: false,
    rating: 5.0,
    numReviews: 120,
    soldCount: 230,
    featured: true,
  },
  {
    name: 'Re:Zero - Rem: Crystal Dress Ver. 1/7 Scale Figure',
    slug: 're-zero-rem-crystal-dress-1-7',
    sku: 'ESTR-REM-777',
    categorySlug: 'anime-figures',
    subCategory: 'Scale 1/7 & 1/4',
    brand: 'eStream / Shibuya Scramble',
    price: 389.99,
    discountPrice: 359.99,
    stockCount: 4,
    images: [
      'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'A masterpiece from Shibuya Scramble Figure. Rem is dynamically sculpted standing amid swirling ice crystals and cascading cerulean ribbons, showcasing translucent dress gradients.',
    attributes: {
      scale: '1/7 Scale',
      character: 'Rem',
      series: 'Re:Zero - Starting Life in Another World',
      material: 'PVC & Clear Resin',
    },
    isPreOrder: true,
    releaseDate: new Date('2026-11-15'),
    rating: 4.95,
    numReviews: 85,
    soldCount: 43,
    featured: true,
  },
  {
    name: 'Evangelion 3.0+1.0 - Asuka Langley Shikinami (White Plugsuit) 1/6 Scale',
    slug: 'evangelion-asuka-langley-white-plugsuit-1-6',
    sku: 'KOTO-EVA-002',
    categorySlug: 'anime-figures',
    subCategory: 'Scale 1/7 & 1/4',
    brand: 'Kotobukiya',
    price: 189.99,
    discountPrice: 0,
    stockCount: 8,
    images: [
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Kotobukiya presents Asuka Langley Shikinami as depicted in Evangelion: 3.0+1.0 Thrice Upon a Time, wearing the new white deep-dive plugsuit atop ruined metal rebar terrain.',
    attributes: {
      scale: '1/6 Scale',
      character: 'Asuka Langley',
      series: 'Neon Genesis Evangelion',
      material: 'PVC',
    },
    isPreOrder: false,
    rating: 4.8,
    numReviews: 32,
    soldCount: 55,
    featured: false,
  },

  // 2. Warhammer 40,000 / Tabletop
  {
    name: 'Warhammer 40,000 - Space Marine Primaris Intercessors Squad',
    slug: 'warhammer-40k-space-marine-primaris-intercessors',
    sku: 'GW-40K-SM-001',
    categorySlug: 'warhammer-40k',
    subCategory: 'Space Marines & Imperium',
    brand: 'Games Workshop',
    price: 65.00,
    discountPrice: 58.50,
    stockCount: 25,
    images: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'The core backbone of any Adeptus Astartes army. Contains 10 multi-part plastic Citadel miniatures equipped with bolt rifles, auto bolt rifles, or stalker bolt rifles.',
    attributes: {
      faction: 'Imperium',
      gameSystem: 'Warhammer 40,000',
      miniatureCount: 10,
      material: 'Citadel High-Impact Polystyrene',
    },
    isPreOrder: false,
    rating: 4.9,
    numReviews: 110,
    soldCount: 310,
    featured: true,
  },
  {
    name: 'Warhammer 40,000 - Combat Patrol: Chaos Space Marines',
    slug: 'warhammer-40k-combat-patrol-chaos-space-marines',
    sku: 'GW-40K-CSM-015',
    categorySlug: 'warhammer-40k',
    subCategory: 'Chaos Space Marines',
    brand: 'Games Workshop',
    price: 160.00,
    discountPrice: 144.00,
    stockCount: 12,
    images: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Unleash the wrath of the Dark Gods! Includes a Dark Apostle with Disciple retainers, 10 Legionaries, 5 Havocs with heavy weapons, and a brutish Helbrute walker.',
    attributes: {
      faction: 'Chaos',
      gameSystem: 'Warhammer 40,000',
      miniatureCount: 19,
      material: 'Citadel Polystyrene',
    },
    isPreOrder: false,
    rating: 4.85,
    numReviews: 64,
    soldCount: 140,
    featured: true,
  },
  {
    name: 'Warhammer 40,000 - Necron Warriors with Canoptek Scarabs',
    slug: 'warhammer-40k-necron-warriors-with-scarabs',
    sku: 'GW-40K-NEC-003',
    categorySlug: 'warhammer-40k',
    subCategory: 'Xenos Factions',
    brand: 'Games Workshop',
    price: 50.00,
    discountPrice: 0,
    stockCount: 18,
    images: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Awaken the undying dynasties. Kit builds 10 shambling metallic Necron Warriors wielding gauss flayers or gauss reapers, plus 3 Canoptek Scarab swarms.',
    attributes: {
      faction: 'Xenos',
      gameSystem: 'Warhammer 40,000',
      miniatureCount: 13,
      material: 'Citadel Polystyrene',
    },
    isPreOrder: false,
    rating: 4.7,
    numReviews: 45,
    soldCount: 180,
    featured: false,
  },
  {
    name: 'Warhammer 40,000: Kill Team - Into the Dark Core Box',
    slug: 'warhammer-kill-team-into-the-dark',
    sku: 'GW-KT-DARK-01',
    categorySlug: 'warhammer-40k',
    subCategory: 'Kill Team',
    brand: 'Games Workshop',
    price: 210.00,
    discountPrice: 189.00,
    stockCount: 3, // Low stock demo!
    images: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Skirmish combat in the claustrophobic corridors of the Space Hulk Gallowdark. Includes Imperial Navy Breachers kill team, Kroot Farstalker Kinband, modular terrain and rules.',
    attributes: {
      faction: 'Imperium',
      gameSystem: 'Kill Team',
      miniatureCount: 24,
      material: 'Citadel Polystyrene',
    },
    isPreOrder: false,
    rating: 4.95,
    numReviews: 76,
    soldCount: 95,
    featured: true,
  },

  // 3. Board Games
  {
    name: 'Scythe: Collector’s Edition Board Game',
    slug: 'scythe-collectors-edition-board-game',
    sku: 'STM-SCY-001',
    categorySlug: 'board-games',
    subCategory: 'Heavy Strategy & Euro',
    brand: 'Stonemaier Games',
    price: 99.99,
    discountPrice: 89.99,
    stockCount: 16,
    images: [
      'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'An engine-building, asymmetric competitive board game set in an alternate-history 1920s period. Lead your faction to conquer territories, enlist recruits, reap resources, and activate monstrous dieselpunk mechs.',
    attributes: {
      minPlayers: 1,
      maxPlayers: 5,
      playtimeMin: 115,
      complexity: 'Heavy',
      language: 'English',
    },
    isPreOrder: false,
    rating: 4.95,
    numReviews: 210,
    soldCount: 420,
    featured: true,
  },
  {
    name: 'Terraforming Mars (Includes Prelude Expansion)',
    slug: 'terraforming-mars-prelude-bundle',
    sku: 'FRYX-TM-004',
    categorySlug: 'board-games',
    subCategory: 'Heavy Strategy & Euro',
    brand: 'FryxGames',
    price: 79.99,
    discountPrice: 69.99,
    stockCount: 20,
    images: [
      'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Corporations compete to transform the red planet into a habitable haven. Manage patents, raise the temperature, flood the oceans, and plant lush forests in one of the highest-rated board games of all time.',
    attributes: {
      minPlayers: 1,
      maxPlayers: 5,
      playtimeMin: 120,
      complexity: 'Heavy',
      language: 'English',
    },
    isPreOrder: false,
    rating: 4.9,
    numReviews: 180,
    soldCount: 390,
    featured: true,
  },
  {
    name: 'Dune: Imperium - Uprising Standalone Sequel',
    slug: 'dune-imperium-uprising',
    sku: 'DW-DUNE-003',
    categorySlug: 'board-games',
    subCategory: 'Heavy Strategy & Euro',
    brand: 'Dire Wolf',
    price: 65.00,
    discountPrice: 0,
    stockCount: 22,
    images: [
      'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Balance military supremacy and political maneuvering on the sands of Arrakis. Introduces sandworms, spy masters, contracts, and an intense six-player team mode.',
    attributes: {
      minPlayers: 1,
      maxPlayers: 6,
      playtimeMin: 90,
      complexity: 'Medium',
      language: 'English',
    },
    isPreOrder: false,
    rating: 4.92,
    numReviews: 95,
    soldCount: 210,
    featured: true,
  },
  {
    name: 'Wingspan - European Expansion Included Edition',
    slug: 'wingspan-bird-collection-board-game',
    sku: 'STM-WING-002',
    categorySlug: 'board-games',
    subCategory: 'Engine Building',
    brand: 'Stonemaier Games',
    price: 65.00,
    discountPrice: 55.00,
    stockCount: 2, // Low stock demo!
    images: [
      'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Winner of the prestigious Kennerspiel des Jahres. You are bird enthusiasts—researchers, bird watchers, ornithologists, and collectors—seeking to discover and attract the best birds to your network of wildlife preserves.',
    attributes: {
      minPlayers: 1,
      maxPlayers: 5,
      playtimeMin: 70,
      complexity: 'Medium',
      language: 'English',
    },
    isPreOrder: false,
    rating: 4.88,
    numReviews: 165,
    soldCount: 350,
    featured: false,
  },
];

module.exports = {
  categoriesData,
  usersData,
  productsData,
};
